### ISSUE TITLE
SDK: problems with cmake on windows - date format and sort

### ISSUE THREAD

**Issue by kglowins** [dream3d/DREAM3D#478] opened 2015-10-22 19:00 UTC
When I try to 'Configure' using cmake gui, there are two places where I get errors:

1) On both Windows 7 and 8.1 there's a problem with line 34 of DREAM3D_SDK/DREAM3D_SDK.cmake ,i.e.,
with "list(SORT MyPluginList)". Commenting this lines solves the problem.

2) On Win 8.1 only, there's a problem with line 830 of DREAM3D\Support\cmp\cmpCMakeMacros.cmake; the message says: index out of range. This is probably because of date format. On Win 7 it looks like this (and the script seems to be adjusted to it):

C:\>date /T
Thu 10/22/2015

while on Windows 8.1, it is:

C:\>date /T
2015-10-22

Modification of the script solves the problem, also it allows for successful compilation using Visual Studio. 
However, I would make sure whether this difference is really caused by different versions of Windows or only by some local settings.

**Comment by kglowins** [comment] 2015-10-22 19:18
I've asked my colleague to test it. Win 7, but in Polish version also gives "2015-10-22", so the problem is not related to version of win itself.

**Comment by imikejackson** [comment] 2015-10-22 23:07
2) Correct you are. The issue is something else so I have simply removed those portions of the CMake and simply put out an empty version string instead. The changes are in the latest version of the Develop branch.

**Comment by imikejackson** [comment] 2015-10-22 23:08
1) I was made aware of the problem late last week and have fixed the issue when creating the SDK on at least OS X. A fix for the precompiled DREAM3D_SDK will be forth coming in the next few weeks but for now the fix is to comment those lines. The line just sorted the plugins alphabetically for the user so the line is really not that important in the larger picture.

**Comment by sdonegan** [comment] 2016-01-11 15:17
Fixed by removing date calls when computing version strings.  If git is not available, CMake will default the version to 0.0.0.

**Closed by sdonegan** 2016-01-11 15:17 UTC
Labels: Bug
